language: rust
cache: cargo
rust:
- stable
script:
- cargo build --release
matrix:
  include:
  - OS_TYPE=centos OS_VERSION=7
    rust: stable
    env:
    - FILENAME=bloxtool-C7-linux-x86_64
  - dist: trusty
    rust: stable
    env:
    - FILENAME=bloxtool-trusty-linux-x86_64
  - os: osx
    rust: stable
    env:
    - FILENAME=bloxtool-osx-x86_64

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FUXxh+M7eldAbJr+IacSiGDN5D1vKa8RSbGZq+udmqXUZZUOrxOTdi0QjNcXD1fEXEXz9nM9Tw4uLG15WTF8CNIGvViKx5tDgr2YATqtuSWctuiLK5WBoCir/3uAS+neuOkJ7TQOOTh+BQJ/AwlbDTN/UEi+V1ZrAimbJqKooix1xsgRXEWHWMc2Q7EnECBMudzDbb83+yVDgKZp+ObcF2rdkEzfMQ7viUY29LazFJt3AL6mq/vVJ18BtlHPmdyMsqu3MOGvw4hgyYXy8/DPl3n+DvN+qmc184zdbTU5Hqj9ngyCCepu7z9s/Of2zy8QefCTwBia+kl/nmWCa+4U9N699sugex6X0x0J7EdLge6KLJ/jN2qG7xAq7LKFCk7py3eStWdftvzatBZS42m5elgUI6LiHKEJ/9lDrn+OquJKVfoiSGtbyPnyz2jB8MzZ9/rOs8mLCeJOb9zpRoBLzzjs89CyZE//qlNC2zIP39WyNpauLatB+IdnffPWQdKKv5Bwx8p5vDjI3szdUzmTJbOm7tRoQlS9VPMPdPSQ+k7+P3uNaZhz4OgbfbW1kzbu5znrE0T4gpIEFYLfRDNWNiPb4knh6s2oAnK1CeHtGY8PtpnufSLAidHZegsSnuBQ75Fq10VD3cHwegENNaDBSR4qZpSzPEVMHjJ8WKEMhE8=
  file_glob: true
  file: target/release/${FILENAME}
  on:
    tags: true
before_deploy:
  - mv target/release/bloxtool target/release/${FILENAME}
notifications:
  email:
    on_success: never