language: rust
cache:
  cargo: true
rust:
- stable
matrix:
  include:
  - os: linux
    script:
    - cargo test
    - cross build ${BUILDARGS} --release
    before_install:
    - sudo apt-get install -y libssl-dev musl musl-dev musl-tools
    - cargo install cross --force
    install:
    - rustup target add x86_64-unknown-linux-musl
    rust: stable
    env:
    - TARGET=x86_64-unknown-linux-musl
    - PKG_CONFIG_ALLOW_CROSS=1
    - BUILDARGS="--target=${TARGET}"
    - FILENAME=bloxtool-C7-linux-x86_64
    dist: trusty
    sudo: required
  - os: osx
    rust: stable
    script:
    - cargo test
    - cargo build --release
    env:
    - FILENAME=bloxtool-osx-x86_64
    - BUILDARGS=""
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: nD0D7PJ5IyP0OxHLl2b/8BSXXpy+cle1Z+zToS5wAXOnr+HFRia2anFlYqnLuxqMXlJCkIAjEIWsZ2TB1LUzZCi+50rVi6yjAdtgjiRdmtVY4NlDDhXeh/wcVBmXOzjPx55A0lE9/mTSje6WD+Ubj25iIey1an1X3uCoxDoJQUn6SiO3lRpDsnJUISFQKLChh68ck37Ir3ANB4lQJHjlkhdVwtd/9/sYYxh8R8iTdN4jOzrdnPxhmhOLvz6otYRIxS10G+N4Z+E49RAvcvJQ0vWcEujQw4qcCN7323Hd59p00lrWquarx0i6d0jiZtP+FW3ume8f/4HVWhRCIz+iAaUa95sqF1Y7i3SI7INniCytl6I+TXgtOE+X37aSH148mxWP2pWr0T3a4KHh6me7yf5GLmBhcxT6g5pTjX6JREsLr6Cdh41fIC4rHmBnVJ0mdnFOvq4vFPZ9wKPSDxsBUI3NEVDcAtWr71IELTNgCa3Qdm8V/BJLf3YQm/U19Ata/YfBecVoS2BVx1ZLN7OnYnoEnsxyt9SxobfTEaOKCKHjUDsYEItPdA0lBcMYPKkNzDgz9TCjx97pRfKTpEwdBOnD/w6F90piOyUzpXuNXP6RZ4eBKDDStrXdV+3fNkSkn+8b8p1qxsmeN0keLs3O4NYucnLREczTFHY9NlnrwvA=
  file: target/release/${FILENAME}
before_deploy:
- mv target/${TARGET}/release/bloxtool target/release/${FILENAME}
notifications:
  email:
    on_success: never
