language: rust
cache: cargo
rust:
- stable
os:
  - linux
  - osx
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: releases
  api_key:
    secure: Ae39hx2naoVkcktirjhlez2zWFk3Tt6alafbSI66C8gKBw0ng3FazP4fji0wbd/SM75sUUBH2/PYLKOScCoJqc9wME3vB1L+K2zeqGdFB3QP3+0Asqi4vfzxYutHWJcnhzOCRQ/YDuv7A0gwrg/G3DDRMPtjG43/BHDRkk1WUO8wxm/4WVWXU41NXadZCT+UU8gcUG36okZH6NC8ZNzaBmd3tXh1F68QJ9XKmAMvSqakuKK4m3EF/v2iZiQ+Rh23Y07PJ7dG6vrRC2B4U+ewmP+ONP2e1zJT9nsL3E9+tPZYsBNOdV1MVBBCfr7SooGGU630VvYb8C8ie15oKJVMh9TPm+lj54eGYIT+l/ka/E1SkaMi7LU3ULaiHfKAcPLZpttYEQuSX6vF0RCflfWozfI8NH/+LKVPGLArk6d9aUsv9jn9byzQ+dfqFtDuJi3QiTur7FR7Qj7czd0LsPgljrqYCzBLDUcOFRoYGKUgNdcCoaG4Cj8nF4b/RyFlwUEi8HPJRPUOqaydjPR05HL8IKNusFPVT2vDk0DZ01SfohF5q+NMlHAZVyeVQygyyT73s/EHusVDDVc+Y826gyCBmj1Z+DA24S3CxplBbdXSq08iNQTGgH1LbRFo9gTpCVpi/JTmEx48QSfyMXMkcfQmH9C+W6nyrwfxgMz9QsgPG8o=
  file: 'target/release/bloxtool'
  on:
    repo: rtucker-mozilla/bloxtool-rs
