language: rust
cache: cargo
rust:
- stable
matrix:
  include:
  - os: linux
    script:
    - cargo test
    - cross build ${BUILDARGS} --release
    before_install:
    - sudo apt-get install -y libssl-dev musl musl-dev musl-tools
    - cargo install cross --force
    install:
    - rustup target add x86_64-unknown-linux-musl
    rust: stable
    env:
    - TARGET=x86_64-unknown-linux-musl
    - PKG_CONFIG_ALLOW_CROSS=1
    - BUILDARGS="--target=${TARGET}"
    - FILENAME=bloxtool-C7-linux-x86_64
    dist: trusty
    sudo: required
  - os: osx
    rust: stable
    script:
    - cargo test
    - cargo build --release
    env:
    - FILENAME=bloxtool-osx-x86_64
    - BUILDARGS=""
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: UeQU79XUL+2BWKZ0Po8ejc5yIO1katSXilTOVFkeGnE/mEB8eJgoY+R/doUPgqbjsgHaOkPDwUUO480+oZPvEAwlrpGHQZe56IMIVZy936HBJqtLkcV4CQN71eJzh3Jrwf7BYnNfm7R9pBCfbxSWJnPXIMZmdLlwvm7XO6Q6NnYMfvrjIynpev83+DloFUUYCAPRwSkxxWkt1BilrE5my5vTo5+ABwlXB1zFf/CnaoB0Q6qD242+nAm7jhuasMWTk8/Tx8IdkZlR4ZezDtQUqnu1gBCIoDHDzXUwixfMzbNSaYb3JXphxKZWABDOdMxr9mrPV+KrGFTIF2pGa/0vl1APcrj+D0IlP4eIO0xrrzSPW5W657veYO19pYlPVWnzKd70iefhhVtZC0LRPOQcTmwEzcIbDWrpkhed1uNOlUUHl+9oSkLY1WK85bNfoNPxU7NejfMFkB0n2s42KQHQ+cIB9kMuJ7ZCJbNcPPJVJH5DT3b/H8wj5wjyRQfU9STFAjtQvKx98JiAsumzPelpPmmPTrCnhRgDlSnphwnqUlhmQh10jmGTN6KlKKPaTmUMzUZUHUB7g7N+0GPucUy/bQ9do4831fHsM9bjgsk25isfY3rwyyfIpvE5B/cgnFeaOMExaCPG0fOAyjspskK8kKyspNN/w2e8SMZfkoOld84=
  file: target/release/${FILENAME}
  on:
    repo: rtucker-mozilla/bloxtool-rs
before_deploy:
- mv target/${TARGET}/release/bloxtool target/release/${FILENAME}
notifications:
  email:
    on_success: never
